
#General Settings
[general]
	#Include wall variants in the game.
	includeWalls = true
	#Include stair variants in the game.
	includeStairs = true
	#Include slab variants in the game.
	includeSlabs = true
	#Include fence variants in the game.
	includeFences = true
	#Include fence gate variants in the game.
	includeGates = true

#Crafting Settings
[crafting]
	#Allows crafting of concrete blocks.
	concreteCrafting = false
	#Allows crafting of grass blocks.
	grassCrafting = false

