name: "release"
on:
  push:
    branches:
      - "1.12.2"
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'AsgardBrasil-1.12.2.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "1.12.2"
        prerelease: true
        title: "AsgardBrasil 1.12.2"
        files: 'AsgardBrasil-1.12.2.zip'
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v4.0.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        username: "Floki dos Workflow's"
        avatar-url: 'https://streamingsbrasil.com/wp-content/uploads/2022/04/vikings-floki-futuro.jpg'
        embed-color: 3066993
        embed-description: |
          Você pode atualizar via Technic já ou baixando manualmente no Github
          
          📜 **Commits**
          ${{ contains(github.event.commits[][message]) }}


        embed-title: '✅ Nova versão disponível para 1.12.2'  