name: "release"
on:
  push:
    branches:
      - "1.12.2"
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'AsgardBrasil-1.12.2.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "1.12.2"
        prerelease: false
        title: "AsgardBrasil"
        files: 'AsgardBrasil-1.12.2.zip'